In [1]:
print("All okay")

All okay


In [13]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

documents = [
    "People watch movie",
    "People watch cricket",
    "People like movie",
    "People like cricket"
]

tokens =[sentence.lower().split() for sentence in documents]
print(tokens)
all_words = [[word] for sentence in tokens for word in sentence]
all_words

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(all_words)
encoder.categories_

for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print(encoded_sentence)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
